# 『pytorch ＆ 深層学習プログラミング』　入門編

## 目次

- [np.trsnspose() (p536)](#nptrsnspose-p536)


## np.trsnspose() (p536)
---
<br>


この関数が行っている行列の変換の仕方が分かりづらかった。

本書よりもっと単純な行列でその変換の仕方を見る。

In [2]:
import numpy as np
n1 = np.arange(1,13,1)
n2 = n1.reshape(2,3,2)
n2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

この行列を`np.transpose`関数で変換してみると

In [3]:
n3 = np.transpose(n2, (0,2,1))
print(n3)
n3.shape

[[[ 1  3  5]
  [ 2  4  6]]

 [[ 7  9 11]
  [ 8 10 12]]]


(2, 2, 3)

正直言うと、この変換がどのような法則で行われているのかわからなかった。公式ドキュメントにはこの変換で**軸を入れ替える**と書いてあるが、それは分かるのである。実際にこの変換がどのような法則によって行われているのか、自分なりにかみ砕いて説明する。

変換は3段階に分けて考えると分かりやすい。

1. 全体の構造を把握する
2. 一番内側の（最小の）格子[]の中身は元の行列のどの部分に相当するか確認する
3. 次に来る内側の（最小の）格子が元の行列のどの部分に相当するか確認する

である。具体的にどういうことなのかは以下の通り

1. `n3.shape`で構造を確認
2. `np.transpose(a,b,c)`の`c`に注目する。この軸が格子の最小単位を決定するので、1．の構造を参考にしつつ元の行列と見比べてみる
3. `np.transpose(a,b,c)`の`b`に注目する。これが次の格子を選ぶ際の軸となる。

<br>

自分の文章力では説明に限界があるので、上に載せたコードの場合どのように考えるかを説明する。

1．について、これは簡単で、`n3.shape`の結果を見ればよい。（今回は（2,2,3））

2．が難しい。今回の場合、`np.transpose(0,2,1)`なので、`1`に注目する。軸「１」は元の行列では（2,`3`,2）の「３」に相当する。

この「３」が元の行列で何を示しているのか。今回大事なのは

**1,3,5の（縦）方向で行列を作る**

という意味である（と思う）。

**新しくできる行列の形は（2,2,3）であり1,3,5の方向で3つの数を取り出せば最小格子の中身が得られる**という事なので、新たな行列の最小格子の一つは[1,3,5]であると分かる。

---横並び比較---

![](image/2022-04-09-11-04-22.png)　　　　　　　　　　　　　　![](image/2022-04-09-11-05-56.png)



新たな行列では[2,4,6]が次に来ている。これはどういうことなのかというのが、3．で分かるようになっている。

`np.transpose(0,2,1)`なので、`2`に注目する。軸「2」というのは元の行列で言うと(2,3,`2`)の「2」であり、これについて大切なのは**1,2や3,4方向で数える**という意味である。

つまりどういうことかと言うと、**元の行列から[1,3,5]の次に取ってくる格子の中身は、1,2方向（横方向）に進んで[2,4,6]にしなさい**という事である。決して[7,9,11]ではないという事だ。

新たにできる行列の形は（2,2,3）なので、以上で（2,3）の1セットは完成である。これをもう1セット作れば、新たな行列の完成である。

ちなみに、np.transpose(`0`,1,2)の「0」はあまり気にしなくても何とかなるというのが今のところの感想で、大事なのはその後ろの2つの軸であるという事を覚えておきたい。

ちなみに以下が、本書のnp.transposeの変換である。

In [5]:
n4 = np.arange(0,24,1)
n5 = n4.reshape(2,3,4)
print(f'n5のshapeは {n5.shape}で、中身は以下の通り')
print(n5)

n5のshapeは (2, 3, 4)で、中身は以下の通り
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [6]:
n6 = np.transpose(n5,(1,2,0))
print(f'n6のshapeは{n6.shape}で、中身は以下の通り')
print(n6)

n6のshapeは(3, 4, 2)で、中身は以下の通り
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
